//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccione
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Direccion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
